### ISSUE TITLE
how export .ipynb to html,I use command to export the chart can not show

### ISSUE THREAD

**Issue by lizhi2013** [napjon/krisk#67]
i use command like this :
ipython nbconvert --to html --template fill mynotebook.ipynb
the question is all the krisk img can not show ....

**Comment by napjon** [comment]
Hi @lizhi2013, have you tried to inject js library by execute 'init_notebook'  first? It's not required when you're in Jupyter because it's injected in every notebook session, but you have to do it manually if you exported in html.

**Comment by napjon** [comment]
Since there is no reply, I assume the issue has been resolved. Feel free to open this thread again.
